name: Kurly Web App Back-end Deploy Workflow

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    name: Build Docker Image Stage
    runs-on: ubuntu-latest

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./docker/Dockerfile
          build-args:
            - DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kurlyapp/be:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: SCP Command to Transfer Files (Send Docker Config)
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker/docker-compose.yml, ./docker/set_env.sh"
          target: "~/app/kurly-be/docker"
          strip_components: 2

  deployment:
    name: Deploy Docker Image Stage
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected with Actions!"
            cd ./app/kurly-be/docker
            ./set_env.sh
            echo "GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}" > .env
            echo "GITHUB_KURLY_BE_SHA=${{ github.sha }}" >> .env
            sudo docker compose down
            sudo docker rmi ghcr.io/sk0x0y/kurlyapp/be:$GITHUB_KURLY_BE_SHA
            sudo docker compose --env-file .env up -d
